### ISSUE TITLE
Deprecated request library usage

### ISSUE THREAD

**Issue by lucasassisrosa** [elastic/site-search-node#9]
Hey there,

this lib is using the node `request` library which has been deprecated recently. Could you replace it with the so-called modern libraries?

![image](https://user-images.githubusercontent.com/49399224/75723629-6b79b700-5cbb-11ea-8608-f2bdd57e32b7.png)

**Comment by yakhinvadim** [comment]
Hey Lucas!

We're currently looking into ways of generating API clients from OpenAPI specifications. When it's done, the new client will have a completely new code and we'll make sure that it doesn't include the `request` package. I can't say when it will be finished, unfortunately. For now, the manual support of this client is limited to fixing major bugs and security vulnerabilities.

Please let me know if you have any more questions.
